name: Create Release PR

on: workflow_dispatch

jobs:
  bump_version:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Commitzen
        run: |
          python -m pip install --upgrade pip
          pip install -U Commitizen

      - name: Bump Version
        id: cz
        run: |
          cz bump --files-only --changelog --yes
          echo "version=$(cz version --project)" >> "$GITHUB_OUTPUT"

      - name: Print Version
        run: echo "Bumping to version ${{ steps.cz.outputs.version }}"

      - name: Stage Changed Files
        run: |
          git add .
          git status

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: 'Release ${{ steps.cz.outputs.version }}'
          body: |
            After merging this PR, tag the merge commit with:
            ```shell
              git tag ${{ steps.cz.outputs.version }}
              git push origin ${{ steps.cz.outputs.version }}
            ```
          commit-message: 'chore: release ${{ steps.cz.outputs.version }}'
          branch: 'release/${{ steps.cz.outputs.version }}'
          add-paths: |
            .cz.yaml
            CHANGELOG.md
            package.json
