name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  check_commit_messages:
    name: Check Commit Messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Commitzen
        run: |
          python -m pip install --upgrade pip
          pip install -U Commitizen
      - name: Check Commit Messages
        run: cz check --rev-range HEAD

  check_code_style:
    name: Check Code Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: '7.21.0'

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
          cache: pnpm

      - name: Install Node Modules
        run: pnpm i --frozen-lockfile

      - name: Check formatting
        run: pnpm format:check

      - name: Lint
        run: pnpm lint
